default_platform(:ios)

platform :ios do
  lane :bump_build_number do
    increment_build_number(xcodeproj: 'COINiDWallet.xcodeproj')
  end

  lane :coin_beta do |options|
    if !options[:coin] || !options[:ticker] || !options[:time]
      puts('Missing options...')
      next
    end

    shRootDir = '../..'; # sh cwd is android/fastlane

    sh("#{shRootDir}/bin/changeCoin #{options[:ticker]}")

    build_app(
      scheme: 'COINiDWallet',
      xcargs: '-allowProvisioningUpdates'
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)

    message_slack(options)
  end

  lane :message_slack do |options|
    slack(
      message: "New #{options[:coin]} Wallet coming to Testflight!",
      default_payloads: [],
      slack_url: ENV['SLACK_URL']
    )
  end
end
